# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-synos"
BBFILE_PATTERN_meta-synos = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-synos = "6"

LAYERDEPENDS_meta-synos = "core"
LAYERSERIES_COMPAT_meta-synos = "kirkstone nanbield scarthgap"
