require conf/distro/poky.conf

DISTRO = "synos"
DISTRO_NAME = "SynOS (Custom Yocto OS)"
DISTRO_VERSION = "1.0.0"
DISTRO_CODENAME = "synos"

MAINTAINER = "SynOS Developers"

# Set default init manager to systemd
DISTRO_FEATURES:append = " systemd"
VIRTUAL-RUNTIME_init_manager = "systemd"
DISTRO_FEATURES_BACKFILL_CONSIDERED += "sysvinit"
VIRTUAL-RUNTIME_initscripts = "systemd-compat-units"

# Optional Distro features
DISTRO_FEATURES:append = " opengl wayland pam x11"
